.PHONY: build
build:
	cat example.py
	mkdir JH

.PHONY: push
push:
	cat example.py
	mkdir JH

.PHONY: deploy
deploy:
	cat example.py
	mkdir JH

.PHONY: debug
debug:
	touch debugComplete.txt

.PHONY: run
run:
	mkdir result
	python3 main.py --port=5050
